version: '3.8'

services:
  web:
    build: .
    command: sh -c "cd /app/eucalyptus_services && python manage.py migrate && gunicorn eucalyptus_services.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.database
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  static_volume: