# Generated by Django 5.0.4 on 2024-04-26 12:59

import artist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artwork', models.ImageField(upload_to=artist.models.song_artwork_directory_path)),
                ('soundcloud_url', models.URLField()),
                ('spotify_url', models.URLField()),
                ('applemusic_url', models.URLField()),
                ('deezer_url', models.URLField()),
                ('youtube_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('artist_logo', models.ImageField(upload_to='artists/<django.db.models.fields.CharField>/')),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('soundcloud', models.URLField()),
                ('spotify', models.URLField()),
                ('apple_music', models.URLField()),
                ('tiktok', models.URLField()),
                ('events', models.ManyToManyField(to='event.event')),
                ('song', models.ManyToManyField(to='artist.song')),
            ],
        ),
    ]
