# Generated by Django 5.0.4 on 2024-04-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='events',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='song',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='artist.artist'),
        ),
    ]
