# Generated by Django 5.0.4 on 2024-04-29 07:51

import artist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_remove_artist_events_remove_artist_song_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_logo',
            field=models.ImageField(upload_to=artist.models.artist_logo_directory_path),
        ),
    ]
