# Generated by Django 5.0.4 on 2024-04-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_remove_song_artist_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artwork',
            field=models.ImageField(upload_to='artwork'),
        ),
    ]
