# Generated by Django 5.0.4 on 2024-04-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_alter_song_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='applemusic_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artwork',
            field=models.ImageField(upload_to='songs/artworks/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='deezer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='soundcloud_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
