# Generated by Django 5.0.4 on 2024-05-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_alter_song_applemusic_url_alter_song_artwork_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='apple_music',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='soundcloud',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
    ]
